name: ab-testing-ML
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo '# model metrics logesticregression' > report.md
          cat metrics.txt >> report.md
          echo "## Data viz" >> report.md
          cml-publish residuals_for_logesticregression.png --md >> report.md
          # cml-send-comment report.md

          echo '# model metrics for decision tree' >> report.md
          cat metrics2.txt >> report.md
          echo "## Data viz" >> report.md
          cml-publish residuals_for_decisiontree.png --md >> report.md
          # cml-send-comment report.md

          echo '# model metrics for randomforest' >> report.md
          cat metrics3.txt >> report.md
          echo "## Data viz" >> report.md
          cml-publish residuals_for_randomforest.png --md >> report.md
          cml-send-comment report.md